steps:
  # Create a release
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'deploy'
    - 'releases'
    - 'create'
    - 'rel-${SHORT_SHA}'
    - '--project'
    - 'demoneil'
    - '--region'
    - 'us-central1'
    - '--delivery-pipeline'
    - 'simple-node-app'
    - '--images'
    - 'my-app-image=gcr.io/demoneil/github.com/neilghosh/simple-node-service:pr-2'
options:
  logging: CLOUD_LOGGING_ONLY
