apiVersion: v1
kind: Service
metadata:
  name: simple-node-app
  labels:
    run: simple-node-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort  
  selector:
    run: simple-node-app